#!/usr/bin/env bash
# =============================================================================
# CodeRAG 2C4G 生产部署脚本（Ubuntu 24.04 / Debian 12）
#
# 用法（root 或 sudo 执行）：
#   sudo bash setup_2c4g.sh <DeepSeek_API_Key> <DashScope_API_Key>
#
# 作用：
#   1. 系统依赖（Python 3.12 / Node 20 / MySQL 8 / Redis / Nginx）+ 2G swap
#   2. clone 仓库到 /opt/coderag（若已存在则跳过）
#   3. Python venv + 依赖（torch CPU 版，避免拉 CUDA）+ asyncmy
#   4. MySQL 调优 + 建库建用户
#   5. 生成生产 .env（DeepSeek LLM / 千问嵌入 / bge-reranker-base 全功能）
#   6. alembic 建表 + seed 嵌入运行时配置（Qwen text-embedding-v3）
#   7. 预下载 bge-reranker-base 到 HF 缓存（否则离线模式加载失败）
#   8. 前端构建 → Nginx 托管静态 + 反代 /api → 127.0.0.1:8085
#   9. systemd 常驻：coderag-api（uvicorn 单 worker）+ coderag-celery（solo）
#
# 前提：Aliyun 安全组已放行 80 端口；服务器能访问 github.com
# =============================================================================
set -euo pipefail

# ── 入参 / 变量 ──────────────────────────────────────────────────────────────
# 支持两种传 key 方式：环境变量（推荐，避免长 key 进命令行被终端搞乱）或位置参数
LLM_KEY="${LLM_KEY:-${1:-}}"          # DeepSeek LLM API key（env LLM_KEY 或 $1）
DASHSCOPE_KEY="${DASHSCOPE_KEY:-${2:-}}"  # DashScope 千问嵌入 key（env DASHSCOPE_KEY 或 $2）

if [ -z "$LLM_KEY" ] || [ -z "$DASHSCOPE_KEY" ]; then
  echo "❌ 用法（推荐，用环境变量传 key）："
  echo "   LLM_KEY='<DeepSeekKey>' DASHSCOPE_KEY='<DashScopeKey>' sudo bash setup_2c4g.sh"
  echo "   或位置参数：sudo bash setup_2c4g.sh <DeepSeekKey> <DashScopeKey>"
  exit 1
fi

APP_DIR="${APP_DIR:-/opt/coderag}"
APP_USER="${APP_USER:-coderag}"
VENV="/home/${APP_USER}/venv"
DB_NAME="coderag"
DB_USER="coderag"
DB_PASS="${DB_PASS:-coderag123}"      # 建议改复杂点（纯字母数字，避免 shell 转义坑）
GIT_REPO="${GIT_REPO:-https://github.com/xun663/codeRAG.git}"
SECRET_KEY="$(openssl rand -hex 32)"
SERVER_IP="$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo 127.0.0.1)"
SWAP_MB=2048

log() { echo -e "\n\033[1;34m[setup]\033[0m $*"; }

# ── 1. 系统依赖 + swap ───────────────────────────────────────────────────────
log "安装系统依赖（Python/Node20/MySQL/Redis/Nginx）"
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y curl ca-certificates git build-essential \
  python3 python3-venv python3-pip \
  mysql-server redis-server nginx \
  pkg-config default-libmysqlclient-dev fail2ban
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

log "创建 2G swap（内存安全垫）"
if ! swapon --show | grep -q swapfile; then
  fallocate -l ${SWAP_MB}M /swapfile
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

# ── 2. 应用用户 + 代码 ───────────────────────────────────────────────────────
log "应用用户 $APP_USER"
id -u "$APP_USER" >/dev/null 2>&1 || useradd -m -s /bin/bash "$APP_USER"

log "代码 → $APP_DIR"
mkdir -p "$APP_DIR"
if [ -f "$APP_DIR/backend/pyproject.toml" ]; then
  # 代码已就位（scp tar 包解压 / 手动放置）：有 .git 则尝试更新，无则直接用
  if [ -d "$APP_DIR/.git" ]; then
    sudo -u "$APP_USER" git -C "$APP_DIR" pull --ff-only || log "⚠️ pull 失败，继续用现有代码"
  else
    log "检测到已有代码（无 .git，跳过 clone）"
  fi
else
  sudo -u "$APP_USER" git clone --depth 1 "$GIT_REPO" "$APP_DIR"
fi
chown -R "$APP_USER":"$APP_USER" "$APP_DIR"

# ── 3. Python venv + 依赖 ────────────────────────────────────────────────────
log "创建 venv + 安装依赖（torch CPU 版）"
# 国内镜像：PyPI 用阿里云，torch 用阿里云 pytorch 镜像（download.pytorch.org 国内访问超时）
PIP_MIRROR="-i https://mirrors.aliyun.com/pypi/simple/ --timeout 100"
sudo -u "$APP_USER" python3 -m venv "$VENV"
"$VENV/bin/pip" install --upgrade pip $PIP_MIRROR >/dev/null
"$VENV/bin/pip" install torch --find-links https://mirrors.aliyun.com/pytorch-wheels/cpu/ --timeout 100
"$VENV/bin/pip" install -e "$APP_DIR/backend" $PIP_MIRROR   # 含 asyncmy、sentence-transformers 等
"$VENV/bin/pip" install "asyncmy>=0.2.9" $PIP_MIRROR        # 双保险：驱动必须可用

# ── 4. MySQL 调优 + 建库 ─────────────────────────────────────────────────────
log "MySQL 调优 + 建库建用户"
cp "$APP_DIR/deploy/mysql/coderag.cnf" /etc/mysql/conf.d/coderag.cnf
systemctl restart mysql
systemctl enable mysql >/dev/null 2>&1 || true
mysql <<SQL
CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

# ── 5. 生产 .env ─────────────────────────────────────────────────────────────
log "生成 backend/.env"
cat > "$APP_DIR/backend/.env" <<'EOF'
# CodeRAG production env (generated by deploy/setup_2c4g.sh)
ENVIRONMENT=production
DEBUG=false
LOG_LEVEL=INFO
SECRET_KEY=__SECRET_KEY__
ACCESS_TOKEN_EXPIRE_MINUTES=60
REFRESH_TOKEN_EXPIRE_DAYS=7

DATABASE_URL=mysql+asyncmy://__DB_USER__:__DB_PASS__@127.0.0.1:3306/__DB_NAME__
DATABASE_URL_SYNC=mysql+pymysql://__DB_USER__:__DB_PASS__@127.0.0.1:3306/__DB_NAME__

REDIS_URL=redis://127.0.0.1:6379/0
CELERY_BROKER_URL=redis://127.0.0.1:6379/1
CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/2

CHROMA_HOST=localhost
CHROMA_PORT=8000
CHROMA_PERSIST_PATH=./data/chroma_db

# LLM：DeepSeek（OpenAI 兼容）
LLM_API_KEY=__LLM_KEY__
DEFAULT_LLM_PROVIDER=openai
OPENAI_API_KEY=__LLM_KEY__
OPENAI_API_BASE=https://api.deepseek.com/v1
OPENAI_MODEL=deepseek-v4-flash

# 嵌入：走云（千问），base_url 由 DB 的 embedding_config 覆盖；此行为 .env 兜底
DEFAULT_EMBEDDING_PROVIDER=openai
OPENAI_EMBEDDING_MODEL=text-embedding-v3

# 重排：bge-reranker-base 全功能保留（2C4G 内存充足）
RERANK_ENABLED=true
RERANK_MODEL=BAAI/bge-reranker-base
RERANK_CANDIDATE_K=30
RERANK_OUTPUT_K=5
RERANK_BATCH_SIZE=16

# 数据清洗
CLEANING_ENABLED=true
CLEANING_NORMALIZE_UNICODE=true
CLEANING_REMOVE_HTML_RESIDUE=true
CLEANING_NORMALIZE_WHITESPACE=true
CLEANING_FILTER_NOISE=true
CLEANING_DEDUPLICATE_PARAGRAPHS=true

UPLOAD_DIR=./data/uploads
MAX_UPLOAD_SIZE_MB=100
CORS_ORIGINS=http://__SERVER_IP__,http://localhost:5173
BACKEND_PORT=8085
EOF

sed -i \
  -e "s/__SECRET_KEY__/${SECRET_KEY}/g" \
  -e "s/__DB_USER__/${DB_USER}/g" \
  -e "s/__DB_PASS__/${DB_PASS}/g" \
  -e "s/__DB_NAME__/${DB_NAME}/g" \
  -e "s/__LLM_KEY__/${LLM_KEY}/g" \
  -e "s/__SERVER_IP__/${SERVER_IP}/g" \
  "$APP_DIR/backend/.env"
chown "$APP_USER":"$APP_USER" "$APP_DIR/backend/.env"

# ── 6. alembic 建表 + seed 嵌入配置 ─────────────────────────────────────────
log "等待 MySQL 就绪（重启后 TCP 监听可能还没起来）"
for i in $(seq 1 30); do
  if mysqladmin ping -h 127.0.0.1 -u root --silent 2>/dev/null; then break; fi
  sleep 2
done

log "alembic 建表"
sudo -u "$APP_USER" bash -c "cd '$APP_DIR/backend' && '$VENV/bin/alembic' upgrade head"

log "seed 嵌入运行时配置（Qwen text-embedding-v3 → dashscope）"
# 用 stdin 直喂 python（不落临时文件，避免 /tmp 权限坑）；root 直跑避免 sudo 重置环境变量
(cd "$APP_DIR/backend" && DASHSCOPE_KEY="$DASHSCOPE_KEY" "$VENV/bin/python" - <<'PYEOF'
import os, asyncio, uuid
from sqlalchemy import select
from app.db.session import async_session_factory
from app.core.monitoring.config_manager import EMBEDDING_CONFIG_KEY
from app.models.feedback import SystemConfig
from app.llm.crypto import encrypt

async def main():
    value = {
        "provider": "openai",
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "model": "text-embedding-v3",
        "dimension": 1024,
        "api_key_encrypted": encrypt(os.environ["DASHSCOPE_KEY"]),
    }
    async with async_session_factory() as db:
        r = await db.execute(select(SystemConfig).where(SystemConfig.config_key == EMBEDDING_CONFIG_KEY))
        row = r.scalar_one_or_none()
        if row:  # 幂等：已存在则更新，避免重复 seed 报唯一约束
            row.config_value = value
        else:
            db.add(SystemConfig(id=uuid.uuid4(), config_key=EMBEDDING_CONFIG_KEY,
                                config_value=value, description="production embedding (Qwen text-embedding-v3)",
                                updated_by=None))
        await db.commit()
        print("✔ embedding_config seeded")

asyncio.run(main())
PYEOF
)

# ── 7. 预下载重排模型 ────────────────────────────────────────────────────────
log "预下载 bge-reranker-base（~1.1GB，首次调用懒加载需要离线缓存）"
# 必须在 coderag 可写目录（其家目录）跑，否则相对路径解析 Permission denied
# HF_ENDPOINT 用国内镜像 hf-mirror.com，避免 huggingface.co 国内下载超时
sudo -u "$APP_USER" bash -c \
  "cd /home/$APP_USER && HOME=/home/$APP_USER HF_HUB_OFFLINE=0 HF_ENDPOINT=https://hf-mirror.com '$VENV/bin/python' -c \"from sentence_transformers import CrossEncoder; CrossEncoder('BAAI/bge-reranker-base'); print('✔ reranker cached')\""

# ── 8. 前端构建 + Nginx ──────────────────────────────────────────────────────
log "前端构建"
cd "$APP_DIR/frontend"
npm ci --no-audit --no-fund >/dev/null
npm run build >/dev/null
rm -rf /var/www/coderag
mkdir -p /var/www/coderag
cp -r dist/* /var/www/coderag/

log "Nginx 配置"
cp "$APP_DIR/deploy/nginx/coderag.conf" /etc/nginx/sites-available/coderag
ln -sf /etc/nginx/sites-available/coderag /etc/nginx/sites-enabled/coderag
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

# ── 9. systemd 常驻 ──────────────────────────────────────────────────────────
log "systemd 单元 + 启动"
cp "$APP_DIR/deploy/systemd/coderag-api.service" /etc/systemd/system/
cp "$APP_DIR/deploy/systemd/coderag-celery.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now redis-server >/dev/null 2>&1 || true
systemctl enable --now coderag-api coderag-celery

# ── 10. fail2ban：SSH 爆破防护 ───────────────────────────────────────────────
log "fail2ban：SSH 10 分钟错 5 次封 1 小时"
cp "$APP_DIR/deploy/fail2ban/jail.local" /etc/fail2ban/jail.local
systemctl enable fail2ban >/dev/null 2>&1 || true
systemctl restart fail2ban
fail2ban-client status sshd | grep -E "Jail list|Currently banned" || true

# ── 11. 验证 ────────────────────────────────────────────────────────────────
log "验证"
sleep 3
API_CODE="$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:8085/docs || echo 000)"
echo "  API /docs → HTTP $API_CODE"
systemctl is-active coderag-api coderag-celery mysql redis-server nginx | sed 's/^/  systemd /'
echo
echo "✅ 部署完成。访问 http://${SERVER_IP}  （首次用 admin / admin123 登录）"
echo "   日志: journalctl -u coderag-api -f   |   journalctl -u coderag-celery -f"
echo "   记得: Aliyun 安全组放行 80 端口；.env 的 DB_PASS 建议改复杂"
