"""add_document_level_gt_and_metrics

Revision ID: 53986c7c67c6
Revises: bec27ed37d26
Create Date: 2026-07-23 14:47:20.229374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53986c7c67c6'
down_revision: Union[str, Sequence[str], None] = 'bec27ed37d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_qa_pairs', sa.Column('relevant_doc_ids', sa.JSON(), nullable=True))
    op.add_column('eval_qa_pairs', sa.Column('relevant_doc_titles', sa.JSON(), nullable=True))
    op.add_column('eval_qa_pairs', sa.Column('answer_span', sa.JSON(), nullable=True))
    op.add_column('eval_results', sa.Column('doc_hit_at_5', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('doc_mrr', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_results', 'doc_mrr')
    op.drop_column('eval_results', 'doc_hit_at_5')
    op.drop_column('eval_qa_pairs', 'answer_span')
    op.drop_column('eval_qa_pairs', 'relevant_doc_titles')
    op.drop_column('eval_qa_pairs', 'relevant_doc_ids')
    # ### end Alembic commands ###
