"""add_ground_truth_fields_and_metrics

Revision ID: bec27ed37d26
Revises: e84fc621615f
Create Date: 2026-07-23 11:41:51.227556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec27ed37d26'
down_revision: Union[str, Sequence[str], None] = 'e84fc621615f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_qa_pairs', sa.Column('ground_truth_chunk_ids', sa.JSON(), nullable=True))
    op.add_column('eval_qa_pairs', sa.Column('ground_truth_chunk_id_type', sa.String(length=20), nullable=True))
    op.add_column('eval_qa_pairs', sa.Column('ground_truth_notes', sa.Text(), nullable=True))
    op.add_column('eval_qa_pairs', sa.Column('subject', sa.String(length=50), nullable=True))
    op.add_column('eval_results', sa.Column('hit_rate_at_5', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('ndcg_at_5', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_results', 'ndcg_at_5')
    op.drop_column('eval_results', 'hit_rate_at_5')
    op.drop_column('eval_qa_pairs', 'subject')
    op.drop_column('eval_qa_pairs', 'ground_truth_notes')
    op.drop_column('eval_qa_pairs', 'ground_truth_chunk_id_type')
    op.drop_column('eval_qa_pairs', 'ground_truth_chunk_ids')
    # ### end Alembic commands ###
